name: 'GdUnit4 CI'
description: 'This GitHub action provides the GdUnit4 test runner'

inputs:
  godot-version:
    required: true
    type: string
  godot-status:
    required: true
    type: string
  godot-net:
    required: false
    type: bool
    default: false
  paths:
    required: true
    type: list
  report-name:
    required: false
    type: string
    default: 'test-report.xml'

runs:
  using: "composite"

  steps:
    - name: "Update Ubuntu"
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get -y install systemd-coredump
        sudo apt update
        sudo apt -y install systemd-coredump

    - name: "Install Godot ${{ inputs.godot-version }}"
      uses: ./.github/actions/godot-install
      with:
        godot-version: ${{ inputs.godot-version }}
        godot-net: ${{ inputs.godot-net }}
        godot-status-version: ${{ inputs.godot-status }}
        godot-bin-name: 'linux.x86_64'
        godot-cache-path: '~/godot-linux'

    - name: "Setup .NET"
      if:  ${{ inputs.godot-net }}
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x

    - name: "Update Project"
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        if ${{ inputs.godot-net }}; then
          dotnet restore
          dotnet build
        fi
        xvfb-run --auto-servernum ~/godot-linux/godot -e --path . -s res://addons/gdUnit4/bin/ProjectScanner.gd --headless --audio-driver Dummy 2> /dev/null

    - name: "Run Unit Tests"
      if: ${{ !cancelled() }}
      uses: ./.github/actions/unit-test
      with:
        godot-bin: '~/godot-linux/godot'
        test-includes: ${{ inputs.paths }}


    - name: "Coredump Check"
      if: ${{ !cancelled() && inputs.godot-net }}
      uses: ./.github/actions/check-coredump
      with:
        artifact-name: "TestRunner-${{ inputs.os }}-${{ inputs.godot-version }}-mono"

    - name: "Publish Unit Test Reports"
      if: ${{ !cancelled() }}
      uses: ./.github/actions/publish-test-report
      with:
        report-name: ${{ inputs.report-name }}