blank_issues_enabled: false
contact_links:
  - name: GdUnit Community Support
    url: https://github.com/MikeSchulze/gdUnit4/discussions
    about: Please ask and answer questions here.

  - name: GdUnit4 Discord Server
    url: https://discord.gg/rdq36JwuaJ
    about: Feel free to join the GdUnit discord server for help and discussion

  - name: GdUnit4 documentation repository
    url: https://github.com/MikeSchulze/gdUnit4/tree/documentation
    about: Please report issues with documentation here.
