name: Feature Request
description: Suggest an idea for GdUnit4
title: "[GD-XXX] Brief description of the feature"
labels: ["enhancement"]
projects: ["GdUnit4/5"]
assignees:
  - MikeSchulze

body:
  - type: markdown
    attributes:
      value: |
        ### Thanks for suggesting a new feature!
        - Please search [existing feature requests](https://github.com/MikeSchulze/gdUnit4/issues?q=label%3Aenhancement%20is%3Aissue) to avoid duplicates
        - Consider if this might be better as a GitHub Discussion to gather community feedback first
        - Check if this feature might already exist in the latest version

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - New assertion/matcher
        - Test runner enhancement
        - IDE/Editor integration
        - Performance improvement
        - Developer experience improvement
        - API/Framework enhancement
        - Documentation/Examples
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: problem-description
    attributes:
      label: Problem/Use Case
      description: What problem would this feature solve or what use case would it enable?
      placeholder: |
        Describe the problem or use case:
        - What are you trying to accomplish?
        - What current limitations are you facing?
        - How does this affect your testing workflow?

        Example: "I'm missing a function to assert that a signal was emitted with specific parameters..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        Describe your proposed solution:
        - What should the feature do?
        - How should it behave?
        - What would the API/interface look like?

        Include code examples if applicable:
        ```gdscript
        # Example of how the feature might be used
        func test_example():
            assert_signal(my_object, "signal_name").was_emitted_with([param1, param2])
        ```
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you considered?
      placeholder: |
        Describe alternative solutions you've thought about:
        - Other ways to solve the same problem
        - Workarounds you're currently using
        - Why those alternatives aren't sufficient
    validations:
      required: false

  - type: textarea
    id: impact-benefits
    attributes:
      label: Impact and Benefits
      description: How would this feature benefit the GdUnit4 community?
      placeholder: |
        Describe the potential impact:
        - Who would benefit from this feature?
        - How common is this use case?
        - What testing scenarios would this improve?
        - Would this make GdUnit4 more competitive with other testing frameworks?
    validations:
      required: false

  - type: textarea
    id: implementation-notes
    attributes:
      label: Implementation Notes
      description: Any technical considerations or implementation ideas?
      placeholder: |
        If you have technical insights:
        - Potential implementation approaches
        - Technical challenges or considerations
        - Integration points with existing code
        - Performance implications
    validations:
      required: false

  - type: textarea
    id: examples-references
    attributes:
      label: Examples and References
      description: Examples from other frameworks or additional context
      placeholder: |
        Include relevant examples:
        - How similar features work in other testing frameworks
        - Links to relevant documentation or discussions
        - Screenshots or mockups (if UI-related)
        - Related issues or pull requests
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you interested in contributing to this feature?
      options:
        - label: I'm willing to contribute code for this feature
        - label: I'm willing to help with testing/feedback
        - label: I'm willing to help with documentation
        - label: I would just like to request this feature
