---

yaml-files:
  - '*.yaml'
  - '*.yml'

extends: default

rules:
  line-length:
    max: 160
  document-start:
    disable
  new-lines:
    type: unix
  new-line-at-end-of-file:
    level: warning
  trailing-spaces:
    level: warning
  comments:
    min-spaces-from-content: 1
