name: 'Formatting Checks'
description: 'Validate YAML, XML, Markdown, and GitHub Actions workflow files'
author: 'MikeSchulze'

inputs:
  validation-ignore-file:
    description: 'File containing validation ignore patterns'
    required: false
    default: 'actions/formatting_checks/.validationignore'

  use-gitignore:
    description: 'Use .gitignore for validation exclusions'
    required: false
    default: 'true'

  actionlint-fail-on-error:
    description: 'Fail the action on actionlint errors'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 'Validate YAML files'
      uses: ibiqlik/action-yamllint@v3
      with:
        config_file: ".github/actions/formatting_checks/.yamllint.yml"

    - name: 'Validate GitHub Actions workflows'
      uses: raven-actions/actionlint@v2
      with:
        fail-on-error: ${{ inputs.actionlint-fail-on-error }}
        matcher: true

    - name: 'Validate JSON and YAML syntax'
      uses: GrantBirki/json-yaml-validate@v2.6.0
      with:
        exclude_file: ${{ inputs.validation-ignore-file }}
        use_gitignore: ${{ inputs.use-gitignore }}
