name: ci-dev

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.yml'
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ci-dev-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        godot-version: ['4.1', '4.1.1', '4.1.2', '4.1.3', '4.2', '4.2.1']

    name: 'Test GdUnit4 ${{ matrix.version }} - 🐧Godot_${{ matrix.godot-version }}'
    uses: MikeSchulze/gdUnit4-action@v1
    with:
      godot-version: ${{ matrix.godot-version }}
      version: master
      paths: |
        res://addons/gdUnit4/test/
      timeout: 10
      report-name: report_gdUnit4-${{ matrix.version }}_Godot${{ matrix.godot-version }}.xml

    name: 'Test GdUnit4 ${{ matrix.version }} - 🐧Godot_${{ matrix.godot-version }}-DotNet'
    uses: MikeSchulze/gdUnit4-action@v1
    with:
      godot-version: ${{ matrix.godot-version }}
      version: master
      godot-net: true
      paths: |
        res://addons/gdUnit4/test/mono/
      timeout: 5
      retries: 3 # We have set the number of repetitions to 3 because Godot mono randomly crashes during C# tests
      report-name: report_gdUnit4-${{ matrix.version }}_Godot${{ matrix.godot-version }}-DotNet.xml

