name: ci-dev

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.yml'
      - '**.jpg'
      - '**.png'
      - '**.md'
  workflow_dispatch:

concurrency:
  group: ci-dev-${{ github.event.number }}
  cancel-in-progress: true

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        godot-version: ['4.0.1', '4.0.2']

    name: "CI on Godot 🐧 v${{ matrix.godot-version }}"
    uses: ./.github/workflows/unit-tests.yml
    with:
      godot-version: ${{ matrix.godot-version }}
